apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet-hunter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planet-hunter
  template:
    metadata:
      labels:
        app: planet-hunter
    spec:
      containers:
      - name: planet-hunter
        image: yourdockerhubusername/planet-hunter:latest
        imagePullPolicy: Always
        env:
        - name: REQUIRE_ALL_CRITERIA
          value: "false"
